name: braintrust-cs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84056
title: Brain Trust CS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#041839'
    - '#eae5d2'
    - '#b8c4b6'
    - '#1b7e9e'
    - '#615c52'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.18105232249945402
purpose: []
