typography_spectrum: 0.84056
color:
  brandColors:
    - '#041839'
    - '#eae5d2'
    - '#b8c4b6'
    - '#1b7e9e'
    - '#615c52'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76103
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gabriel Pagola
  email: gpagola@braintrust-cs.com
  url: www.braintrust-cs.com
name: braintrust-cs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Brain Trust CS
purpose: []
